// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtXxM5Lhgx6PH9EClvTakYJSSaIvGSsMc',
    appId: '1:706007930828:android:50947f725649c133f9ef69',
    messagingSenderId: '706007930828',
    projectId: 'shoppingapp-e1ddc',
    storageBucket: 'shoppingapp-e1ddc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKVR62BA8xsdDkF-83I9TahGxG17is_Kk',
    appId: '1:706007930828:ios:af4577abf19f66a1f9ef69',
    messagingSenderId: '706007930828',
    projectId: 'shoppingapp-e1ddc',
    storageBucket: 'shoppingapp-e1ddc.firebasestorage.app',
    androidClientId: '706007930828-d3okvs5aee4e14bv9c184crin33rm2jc.apps.googleusercontent.com',
    iosClientId: '706007930828-9mkhkaqrmr9ftuj4ja6bgme3kuma1dj9.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceApp',
  );

}